<?php

namespace Tests\Traits;

trait MercadolibreBodyTraitTest
{
    protected $shipmentResponse = [
        'substatus_history' => [],
        'snapshot_packing' => [
            'snapshot_id' => 'ece1ae2a-44d2-48c6-afe2-e23597871ba6',
            'pack_hash' => '1',
        ],
        'receiver_id' => 1652276660,
        'base_cost' => 2589.99,
        'status_history' => [
            'date_shipped' => '2024-01-28T23:57:35.169-04:00',
            'date_returned' => null,
            'date_delivered' => '2024-01-29T00:02:19.543-04:00',
            'date_first_visit' => '2024-01-29T00:02:19.543-04:00',
            'date_not_delivered' => null,
            'date_cancelled' => null,
            'date_handling' => '2024-01-28T23:50:26.000-04:00',
            'date_ready_to_ship' => '2024-01-28T23:50:27.086-04:00',
        ],
        'type' => 'forward',
        'return_details' => null,
        'sender_id' => 1652273320,
        'mode' => 'me2',
        'order_cost' => 75000,
        'priority_class' => [
            'id' => null,
        ],
        'service_id' => 906184,
        'shipping_items' => [
            [
                'domain_id' => null,
                'quantity' => 1,
                'dimensions_source' => [
                    'origin' => 'categories',
                    'id' => 'MLA1405372503__1',
                ],
                'description' => 'Botella Fox Botella De Agua Base - 22 Oz Transparente Fox Color Agua',
                'id' => 'MLA1405372503',
                'user_product_id' => 'MLAU139561832',
                'sender_id' => 1652273320,
                'dimensions' => '8.0x8.0x25.0,150.0',
            ],
        ],
        'tracking_number' => '43052469151',
        'cost_components' => [
            'loyal_discount' => 0,
            'special_discount' => 0,
            'compensation' => 0,
            'gap_discount' => 0,
            'ratio' => 4661.98,
        ],
        'id' => 43052469151,
        'tracking_method' => null,
        'last_updated' => '2024-01-29T00:02:23.199-04:00',
        'items_types' => [
            'new',
        ],
        'comments' => null,
        'substatus' => null,
        'date_created' => '2024-01-28T23:50:14.073-04:00',
        'date_first_printed' => '2024-01-28T23:51:09.641-04:00',
        'created_by' => 'receiver',
        'application_id' => null,
        'shipping_option' => [
            'processing_time' => null,
            'cost' => 0,
            'estimated_schedule_limit' => [
                'date' => null,
            ],
            'shipping_method_id' => 512747,
            'estimated_delivery_final' => [
                'date' => '2024-01-29T00:00:00.000-03:00',
                'offset' => 480,
            ],
            'buffering' => [
                'date' => null,
            ],
            'pickup_promise' => [
                'from' => null,
                'to' => null,
            ],
            'list_cost' => 2071.99,
            'estimated_delivery_limit' => [
                'date' => '2024-01-29T00:00:00.000-03:00',
                'offset' => 72,
            ],
            'priority_class' => [
                'id' => null,
            ],
            'delivery_promise' => 'estimated',
            'delivery_type' => 'estimated',
            'estimated_handling_limit' => [
                'date' => '2024-01-29T00:00:00.000-03:00',
            ],
            'estimated_delivery_time' => [
                'date' => '2024-01-29T00:00:00.000-03:00',
                'pay_before' => '2024-01-29T18:00:00.000-03:00',
                'schedule' => null,
                'unit' => 'hour',
                'offset' => [
                    'date' => null,
                    'shipping' => null,
                ],
                'shipping' => 0,
                'time_frame' => [
                    'from' => null,
                    'to' => null,
                ],
                'handling' => 0,
                'type' => 'known',
            ],
            'name' => 'Prioritario a domicilio',
            'id' => 271385617,
            'estimated_delivery_extended' => [
                'date' => '2024-01-29T00:00:00.000-03:00',
                'offset' => 72,
            ],
            'currency_id' => 'ARS',
        ],
        'tags' => [
            'test_shipment',
        ],
        'sender_address' => [
            'country' => [
                'id' => 'AR',
                'name' => 'Argentina',
            ],
            'address_line' => 'XXXXXXX',
            'types' => [
                'logistic_center_ARP16522733201',
                'self_service_partner',
            ],
            'scoring' => null,
            'agency' => null,
            'city' => [
                'id' => null,
                'name' => 'Barrio 123',
            ],
            'geolocation_type' => 'APPROXIMATE',
            'latitude' => 0,
            'municipality' => [
                'id' => null,
                'name' => null,
            ],
            'location_id' => null,
            'street_name' => 'XXXXXXX',
            'zip_code' => 'XXXXXXX',
            'geolocation_source' => null,
            'intersection' => null,
            'street_number' => 'XXXXXXX',
            'comment' => 'XXXXXXX',
            'id' => null,
            'state' => [
                'id' => 'AR-C',
                'name' => 'Capital Federal',
            ],
            'neighborhood' => [
                'id' => null,
                'name' => null,
            ],
            'geolocation_last_updated' => null,
            'longitude' => 0,
        ],
        'sibling' => [
            'reason' => null,
            'sibling_id' => null,
            'description' => null,
            'source' => null,
            'date_created' => null,
            'last_updated' => null,
        ],
        'return_tracking_number' => null,
        'site_id' => 'MLA',
        'carrier_info' => null,
        'market_place' => 'MELI',
        'receiver_address' => [
            'country' => [
                'id' => 'AR',
                'name' => 'Argentina',
            ],
            'address_line' => 'Calle Paunero SN',
            'types' => [],
            'scoring' => null,
            'agency' => null,
            'city' => [
                'id' => 'TUxBQlBBTDI1MTVa',
                'name' => 'Palermo',
            ],
            'geolocation_type' => 'APPROXIMATE',
            'latitude' => -34.581971,
            'municipality' => [
                'id' => null,
                'name' => null,
            ],
            'location_id' => null,
            'street_name' => 'Calle Paunero',
            'zip_code' => '1425',
            'geolocation_source' => 'map-verified',
            'delivery_preference' => 'residential',
            'intersection' => null,
            'street_number' => 'SN',
            'receiver_name' => 'TEST USER BUYER',
            'comment' => '2B Referencia: Entre test y test',
            'id' => 1354735172,
            'state' => [
                'id' => 'AR-C',
                'name' => 'Capital Federal',
            ],
            'neighborhood' => [
                'id' => null,
                'name' => null,
            ],
            'geolocation_last_updated' => '2024-01-23T23:24:55.157Z',
            'receiver_phone' => 'XXXXXXX',
            'longitude' => -58.408932,
        ],
        'customer_id' => null,
        'order_id' => 2000007482586526,
        'quotation' => null,
        'status' => 'delivered',
        'logistic_type' => 'self_service',
    ];

    protected $costResponse = [
        'receiver' => [
            'compensations' => [],
            'cost' => 2330.99,
            'discounts' => [
                [
                    'rate' => 0.1,
                    'type' => 'loyal',
                    'promoted_amount' => 259,
                ],
            ],
            'user_id' => 1652276660,
            'cost_details' => [
                [
                    'sender_id' => 1652273320,
                    'amount' => 2330.99,
                ],
            ],
            'save' => 0,
            'compensation' => 0,
        ],
        'gross_amount' => 2589.99,
        'senders' => [
            [
                'compensations' => [],
                'charges' => [
                    'charge_flex' => 0,
                ],
                'cost' => 0,
                'discounts' => [],
                'user_id' => 1652273320,
                'save' => 0,
                'compensation' => 0,
            ],
        ],
    ];

    protected $shipmentBodyRequest = [
        '_id' => '57d46e5c-8e4f-4174-a6fb-d8b969cce274',
        'topic' => 'shipments',
        'resource' => '/shipments/43052469151',
        'user_id' => 1652273320,
        'application_id' => 3885598677369409,
        'sent' => '2024-01-29T03:57:35.321Z',
        'attempts' => 1,
        'received' => '2024-01-29T03:57:35.271Z',
        'actions' => [],
    ];

    protected $orderBodyResponse = [
        'id' => 2000007546497076,
        'date_created' => '2024-02-06T12:11:59.000-04:00',
        'last_updated' => '2024-02-06T12:21:04.000-04:00',
        'expiration_date' => '2024-03-05T12:12:00.000-04:00',
        'date_closed' => '2024-02-06T12:12:00.000-04:00',
        'comment' => null,
        'pack_id' => null,
        'pickup_id' => null,
        'fulfilled' => false,
        'hidden_for_seller' => null,
        'buying_mode' => 'buy_equals_pay',
        'shipping_cost' => null,
        'application_id' => null,
        'mediations' => [
            [
                'id' => 5248921602,
            ],
        ],
        'total_amount' => 1000,
        'paid_amount' => 0,
        'coupon' => [
            'amount' => 0,
            'id' => null,
        ],
        'order_items' => [
            [
                'item' => [
                    'id' => 'MLA1405372503',
                    'title' => 'Botella Fox Botella De Agua Base - 22 Oz Transparente Fox Color Agua',
                    'category_id' => 'MLA393762',
                    'variation_id' => null,
                    'seller_custom_field' => null,
                    'variation_attributes' => [],
                    'warranty' => 'Sin garantía',
                    'condition' => 'new',
                    'seller_sku' => null,
                    'global_price' => null,
                    'net_weight' => null,
                    'user_product_id' => 'MLAU139561832',
                ],
                'quantity' => 1,
                'requested_quantity' => [
                    'measure' => 'unit',
                    'value' => 1,
                ],
                'picked_quantity' => null,
                'unit_price' => 1000,
                'full_unit_price' => 1000,
                'currency_id' => 'ARS',
                'manufacturing_days' => null,
                'sale_fee' => 755,
                'listing_type_id' => 'gold_special',
                'base_exchange_rate' => null,
                'base_currency_id' => null,
                'element_id' => null,
                'discounts' => null,
                'bundle' => null,
                'compat_id' => null,
            ],
        ],
        'currency_id' => 'ARS',
        'payments' => [
            [
                'id' => 71707219099,
                'order_id' => 2000007546497076,
                'payer_id' => 1652276660,
                'collector' => [
                    'id' => 1652273320,
                ],
                'card_id' => null,
                'reason' => 'Botella Fox Botella De Agua Base - 22 Oz Transparente Fox Color Agua',
                'site_id' => 'MLA',
                'payment_method_id' => 'account_money',
                'currency_id' => 'ARS',
                'installments' => 1,
                'issuer_id' => '2005',
                'atm_transfer_reference' => [
                    'transaction_id' => null,
                    'company_id' => null,
                ],
                'coupon_id' => null,
                'activation_uri' => null,
                'operation_type' => 'regular_payment',
                'payment_type' => 'account_money',
                'available_actions' => [
                    '',
                ],
                'status' => 'refunded',
                'status_code' => null,
                'status_detail' => 'refunded',
                'transaction_amount' => 1000,
                'transaction_amount_refunded' => 3589.99,
                'taxes_amount' => 0,
                'shipping_cost' => 2589.99,
                'coupon_amount' => 0,
                'overpaid_amount' => 0,
                'total_paid_amount' => 3589.99,
                'installment_amount' => null,
                'deferred_period' => null,
                'date_approved' => '2024-02-06T12:12:00.000-04:00',
                'transaction_order_id' => null,
                'date_created' => '2024-02-06T12:12:00.000-04:00',
                'date_last_modified' => '2024-02-06T12:19:48.000-04:00',
                'marketplace_fee' => 755,
                'reference_id' => null,
                'authorization_code' => null,
            ],
        ],
        'shipping' => [
            'id' => 43079767684,
        ],
        'status' => 'cancelled',
        'status_detail' => null,
        'tags' => [
            'catalog',
            'not_delivered',
            'not_paid',
            'test_order',
        ],
        'internal_tags' => [],
        'feedback' => [
            'seller' => [
                'id' => 9041934948256,
            ],
            'buyer' => null,
        ],
        'context' => [
            'channel' => 'marketplace',
            'site' => 'MLA',
            'flows' => [
                'catalog',
            ],
            'application' => null,
            'product_id' => null,
            'store_id' => null,
        ],
        'seller' => [
            'id' => 1652273320,
        ],
        'buyer' => [
            'id' => 1652276660,
            'nickname' => 'TESTUSER1712952818',
            'first_name' => 'Test',
            'last_name' => 'Test',
        ],
        'taxes' => [
            'amount' => null,
            'currency_id' => null,
            'id' => null,
        ],
        'cancel_detail' => [
            'group' => 'shipment',
            'code' => 'feedback_shipment_wrong_address',
            'description' => 'There is a feedback from seller with the reason wrong_receiver_address',
            'requested_by' => 'seller',
            'date' => '2024-02-06T12:20:47.000-04:00',
            'application_id' => '1576914210470801',
        ],
        'manufacturing_ending_date' => null,
        'order_request' => [
            'change' => null,
            'return' => null,
        ],
    ];
}
